import test from 'node:test';
import assert from 'node:assert/strict';
import { runAudit } from '../eval/rag-pilot/fact-precert-engineering-audit.mjs';

test('Fact pre-certification engineering boundary audit remains deterministic and side-effect free', async () => {
  const result = await runAudit();
  assert.equal(result.audit_status, 'READY_FOR_GPT_REVIEW');
  assert.equal(result.fact_engineering_boundary, 'PASS');
  assert.equal(result.fact_drift_control, 'PASS');
  assert.equal(result.score.total, 27);
  assert.equal(result.score.failed, 0);
  assert.equal(result.p0_critical_drift_count, 0);
  assert.equal(result.p1_engineering_debt_count, 0);
  assert.equal(result.provider_calls, 0);
  assert.equal(result.production_db_writes, 0);
  assert.equal(result.fact_persistence, 0);
  assert.equal(result.gold_mutations, 0);
  assert.equal(result.mapping_production_actions, 0);
  assert.equal(result.claim_production_actions, 0);
  assert.equal(result.writer_production_actions, 0);
  assert.equal(result.stale_v2_field_reference_count, 0);
  assert.equal(result.candidate_direct_downstream_path_count, 0);
  assert.equal(result.grounding_source_authority, 'FROZEN_BACKEND_SNAPSHOT');
  assert.equal(result.unknown_source_ref_behavior, 'FAIL_CLOSED');
  assert.equal(result.source_snapshot_drift_regression, 'PASS');
  assert.equal(result.material_quarantine_regression, 'PASS');
  assert.equal(result.canonicalizer_new_business_semantics, 0);
  assert.equal(result.critical_grounding_escape, 0);
  assert.equal(result.fact_mapping_currentness_regression, 'PASS');
  assert.equal(result.downstream_authority_expansion_count, 0);
  assert.equal(result.claim_currentness_regression, 'PASS');
  assert.equal(result.writer_snapshot_drift_regression, 'PASS');
  assert.equal(result.model_telemetry_conflation, 'NO');
  assert.equal(result.task_config_version_pairing, 'PASS');
  assert.equal(result.schema_retry_path_count, 0);
  assert.equal(result.semantic_empty_retry_path_count, 0);
  assert.equal(result.grounding_retry_path_count, 0);
  assert.equal(result.auto_reextraction_path_count, 0);
  assert.equal(result.v21_production_persistence_path, 'NONE');
  assert.equal(result.eval_artifact_production_import_path_count, 0);
  assert.equal(result.secret_scan, 'PASS');
});
